include:
  - proxy.yaml

services:
  web:
    container_name: "web-app"
    build:
      context: .
      dockerfile: Dockerfile.python

    networks:
      backend:
        ipv4_address: 172.20.0.5
    restart: always
    environment:
      DB_HOST: db  
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
    #ports:
      #- "8080:5000"

  db:
    image: mysql:8
    container_name: "mysql_db"
    networks:
      backend:
        ipv4_address: 172.20.0.10
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
